### ISSUE TITLE
Quick question

### ISSUE THREAD

**Issue by Tenome** [ValleyBell/vgmplay-libvgm#3]
VGMRips keeps telling me that the captcha code is incorrect and refuses to let me sign up, so I can't post this question in the VGMPlay / in_vgm thread.

I'm new to playing emulated chip music (so far all I've done is setup Roland Canvas VA and install vgmplay), so I was wondering about playing music from a library full of various chips. I noticed there's an option to switch between sound chips. Does VGMPlay automatically switch to the correct chip when playing the music back? I generally use the foobar plugin, but it looks like that's no longer being updated.

Battle Garegga for example is on the YM2151. Does VGMPlayer automatically switch to YM2151 if I had it set to, say, SEGA PCM in the options?

Thanks.

**Comment by ValleyBell** [comment]
The options let you choose a different *emulators* (often called "sound cores") for the respective sound chips. They don't let you switch sound chips.

For example, you can select one of 3 different emulators for the YM2612: GenesisPlus GX, NukedOPN2 and Gens.
Those all emulate the YM2612, but are written by different people. Some may be more accurate to the actual hardware. (All Nuked* emulators are highly accurate, but also CPU-heavy.) Some of them may sound bad by today's standards due to being ancient. (e.g. Gens)
The default setting is usually a good mix between accuracy and not being hard on the CPU.

(Hint: In order to solve the vgmrips captcha, you need to carefully read the small print of the "Confirmation code" instructions.)

**Comment by Tenome** [comment]
> The options let you choose a different _emulators_ (often called "sound cores") for the respective sound chips. They don't let you switch sound chips.

Hm, either I'm looking at the wrong thing or we're not on the same page. What's this then? This is what my original question was about. Or are these just settings that I can adjust for each chip, and I don't have to worry about having the wrong chip selected? I actually don't see where to select the three different emulators.
![ss (2021-03-11 at 04 07 03)](https://user-images.githubusercontent.com/12216081/110855386-45023a80-8284-11eb-8918-2fb4ffad9670.png)

**Comment by ValleyBell** [comment]
Ahh, you mean THAT.

Those are just the options that let you control per-channel muting and other options for each chip.

**Comment by Tenome** [comment]
Ahh, okay cool. I'll look up where to select the emulation core then and see if I want to change it. Thanks for clarifying.
