### ISSUE TITLE
Detech libAO in CMake

### ISSUE THREAD

**Issue by lazydogP** [ValleyBell/vgmplay-libvgm#5]
Hi. I tried to build vgmplay on macOS, and it couldn't find `libao` installed by Homebrew. After some struggling searching, it turns out the solution is already in libvgm.
https://github.com/ValleyBell/libvgm/commit/8b3d7d975e93e50861529a25f5eda23a20fb37af
It would be great to sync it with vgmplay.

**Comment by ValleyBell** [comment]
The dependency chain between VGMPlay and libvgm is unfortunately quite messy right now.

- libvgm has the proper find modules
- libvgm executes `find_package`
- libvgm links to libraries like "libAO"
- VGMPlay just imports libvgm + links to it
- VGMPlay doesn't do any "find_package" stuff by itself for the dependencies that libvgm pulls in -> it fails in some cases (like libAO)

The clean solution would be to add `find_dependency` lines to the CMake configure file that libvgm generates.
Because those dependencies change depending on the selected libvgm build parameters, this requires some scripting.
Unfortunately I didn't have time to work on that so far and I also keep forgetting about it.

The dirty temporary solution for local builds is shown in #2.

**Comment by ValleyBell** [comment]
Fixed by 7059fe5f13762babb900c889235f489d34b3ef48 and a400942205ebc249ad2a6ab42d4e39610bd5cc8d.
